#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
icingabotDirectory="/usr/local/icingaBot"

start() {
   pid=$(ps aux | grep icingabot.pl | grep -v grep | tr -s ' ' | cut -d' ' -f2)
   if [ "$pid" = "" ]; then
        echo "Launching Icingabot"
        cd $icingabotDirectory
        perl icingabot.pl > /dev/null 2>&1 &
   else 
        echo "Icingabot is already started"
   fi
}

stop() {
   echo "Stoping IcingaBot"
   pid=$(ps aux | grep icingabot.pl | grep -v grep | tr -s ' ' | cut -d' ' -f2)
   if [ "$pid" = "" ]; then
        echo "Icingabot was already stopped"
   else
        echo "Killing PID: $pid"
        kill -9 $pid
        echo "Done"
   fi
}

restart() {
   stop;
   sleep 1;
   start;
}

status() {
   pid=$(ps aux | grep icingabot.pl | grep -v grep | tr -s ' ' | cut -d' ' -f2)
   if [ "$pid" = "" ]; then
        echo "Icingabot is not running"
   else
        echo "Icingabot is running\nPID number: $pid"
   fi 
}

case $1 in 
start)
        start;;
stop)
        stop;;
restart)
        restart;;
status)
        status;;
*)
        echo "Usage: ./icingaBot (start|stop|restart|status)";;
esac
