#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
icingabotDirectory="/usr/local/icingaBot"

start() {
   pid=$(ps aux | egrep '(icingabot.pl)|(launchIcingaBot.sh)' | grep -v grep | tr -s ' ' | cut -d' ' -f2 | tr '\n' ' ')
   if [ "$pid" = "" ]; then
        echo "Launching Icingabot"
        cd $icingabotDirectory && $icingabotDirectory/launchIcingaBot.sh > /dev/null 2>&1 &
   else 
        echo "Icingabot is already started"
   fi
}

stop() {
   echo "Stoping IcingaBot"
   pid=$(ps aux | egrep '(icingabot.pl)|(launchIcingaBot.sh)' | grep -v grep | tr -s ' ' | cut -d' ' -f2 | tr '\n' ' ')
   if [ "$pid" = "" ]; then
        echo "Icingabot was already stopped"
   else
        for i in $pid; do
                echo "Killing PID: $i"
                kill -9 $i
                echo "Done"
        done
   fi
}

restart() {
   stop;
   sleep 1;
   start;
}

status() {
   pid=$(ps aux | egrep '(icingabot.pl)|(launchIcingaBot.sh)' | grep -v grep | tr -s ' ' | cut -d' ' -f2 | tr '\n' ' ')
   if [ "$pid" = "" ]; then
        echo "Icingabot is not running"
   else
        echo "Icingabot is running\nPID number: $pid"
   fi 
}

case $1 in 
start)
        start;;
stop)
        stop;;
restart)
        restart;;
status)
        status;;
*)
        echo "Usage: ./icingaBot (start|stop|restart|status)";;
esac
